module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
       [
         "sdk",
         "core",
         "ai",
         "agents",
         "audit",
         "auth",
         "billing",
         "blob",
         "connectors",
         "data",
         "governance",
         "lineage",
         "observability",
         "ontology",
         "pipelines",
         "schedules",
         "webhooks",
         "workflows",
         "repo",
         "deps",
         "ci",
         "release",
         "docs",
         "scripts",
         "templates",
       ],
    ],
    "header-max-length": [2, "always", 100],
  },
  ignores: [(message) => message.startsWith("Merge ") || message.startsWith('Revert "')],
};
