name: Documentation issue
description: Report a documentation problem
labels: [documentation]
body:
  - type: input
    id: location
    attributes:
      label: Documentation location
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What should change?
    validations:
      required: true
