"""Typed API resource for the audit endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Audit(APIResource):
    """Methods for the audit API endpoints."""

    def get_audit_events(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /audit/events."""
        return self._request(
            Operation("GET", "/audit/events"),
            path_params=(),
            query=query,
        )

    def get_audit_events_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /audit/events/{param}."""
        return self._request(
            Operation("GET", "/audit/events/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def post_audit_events(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /audit/events."""
        return self._request(
            Operation("POST", "/audit/events"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_audit_events_batch(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /audit/events/batch."""
        return self._request(
            Operation("POST", "/audit/events/batch"),
            path_params=(),
            query=query,
            body=body,
        )
