"""Typed API resource for the data endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Data(APIResource):
    """Methods for the data API endpoints."""

    def get_data_aggregations_aggregations(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/aggregations/aggregations."""
        return self._request(
            Operation("GET", "/data/aggregations/aggregations"),
            path_params=(),
            query=query,
        )

    def get_data_aggregations_aggregations_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/aggregations/aggregations/{param}."""
        return self._request(
            Operation("GET", "/data/aggregations/aggregations/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_archival_archival_policies(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/archival/archival/policies."""
        return self._request(
            Operation("GET", "/data/archival/archival/policies"),
            path_params=(),
            query=query,
        )

    def get_data_archival_archival_policies_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/archival/archival/policies/{param}."""
        return self._request(
            Operation("GET", "/data/archival/archival/policies/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_enrichment_enrichment_profiles(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/enrichment/enrichment/profiles."""
        return self._request(
            Operation("GET", "/data/enrichment/enrichment/profiles"),
            path_params=(),
            query=query,
        )

    def get_data_enrichment_enrichment_profiles_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/enrichment/enrichment/profiles/{param}."""
        return self._request(
            Operation("GET", "/data/enrichment/enrichment/profiles/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_exports_exports(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/exports/exports."""
        return self._request(
            Operation("GET", "/data/exports/exports"),
            path_params=(),
            query=query,
        )

    def get_data_exports_exports_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/exports/exports/{param}."""
        return self._request(
            Operation("GET", "/data/exports/exports/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_normalization_normalization_profiles(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/normalization/normalization/profiles."""
        return self._request(
            Operation("GET", "/data/normalization/normalization/profiles"),
            path_params=(),
            query=query,
        )

    def get_data_normalization_normalization_profiles_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/normalization/normalization/profiles/{param}."""
        return self._request(
            Operation("GET", "/data/normalization/normalization/profiles/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_quality_quality_rulesets(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/quality/quality/rulesets."""
        return self._request(
            Operation("GET", "/data/quality/quality/rulesets"),
            path_params=(),
            query=query,
        )

    def get_data_quality_quality_rulesets_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/quality/quality/rulesets/{param}."""
        return self._request(
            Operation("GET", "/data/quality/quality/rulesets/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_schemas_schemas(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/schemas/schemas."""
        return self._request(
            Operation("GET", "/data/schemas/schemas"),
            path_params=(),
            query=query,
        )

    def get_data_schemas_schemas_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/schemas/schemas/{param}."""
        return self._request(
            Operation("GET", "/data/schemas/schemas/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_serving_serving_products(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/serving/serving/products."""
        return self._request(
            Operation("GET", "/data/serving/serving/products"),
            path_params=(),
            query=query,
        )

    def get_data_serving_serving_products_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/serving/serving/products/{param}."""
        return self._request(
            Operation("GET", "/data/serving/serving/products/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_streams_streams(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/streams/streams."""
        return self._request(
            Operation("GET", "/data/streams/streams"),
            path_params=(),
            query=query,
        )

    def get_data_streams_streams_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/streams/streams/{param}."""
        return self._request(
            Operation("GET", "/data/streams/streams/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_sync_sync_jobs(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /data/sync/sync/jobs."""
        return self._request(
            Operation("GET", "/data/sync/sync/jobs"),
            path_params=(),
            query=query,
        )

    def get_data_sync_sync_jobs_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/sync/sync/jobs/{param}."""
        return self._request(
            Operation("GET", "/data/sync/sync/jobs/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_transformations_transformations(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/transformations/transformations."""
        return self._request(
            Operation("GET", "/data/transformations/transformations"),
            path_params=(),
            query=query,
        )

    def get_data_transformations_transformations_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/transformations/transformations/{param}."""
        return self._request(
            Operation("GET", "/data/transformations/transformations/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def post_data_aggregations_aggregations(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/aggregations/aggregations."""
        return self._request(
            Operation("POST", "/data/aggregations/aggregations"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_aggregations_aggregations_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/aggregations/aggregations/{param}/executions."""
        return self._request(
            Operation("POST", "/data/aggregations/aggregations/{param}/executions"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_archival_archival_policies(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/archival/archival/policies."""
        return self._request(
            Operation("POST", "/data/archival/archival/policies"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_archival_archival_policies_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/archival/archival/policies/{param}/executions."""
        return self._request(
            Operation("POST", "/data/archival/archival/policies/{param}/executions"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_enrichment_enrichment_profiles(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/enrichment/enrichment/profiles."""
        return self._request(
            Operation("POST", "/data/enrichment/enrichment/profiles"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_enrichment_enrichment_profiles_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/enrichment/enrichment/profiles/{param}/executions."""
        return self._request(
            Operation(
                "POST", "/data/enrichment/enrichment/profiles/{param}/executions"
            ),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_exports_exports(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/exports/exports."""
        return self._request(
            Operation("POST", "/data/exports/exports"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_exports_exports_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/exports/exports/{param}/executions."""
        return self._request(
            Operation("POST", "/data/exports/exports/{param}/executions"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_normalization_normalization_profiles(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/normalization/normalization/profiles."""
        return self._request(
            Operation("POST", "/data/normalization/normalization/profiles"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_normalization_normalization_profiles_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/normalization/normalization/profiles/{param}/executions."""
        return self._request(
            Operation(
                "POST", "/data/normalization/normalization/profiles/{param}/executions"
            ),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_quality_quality_rulesets(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/quality/quality/rulesets."""
        return self._request(
            Operation("POST", "/data/quality/quality/rulesets"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_quality_quality_rulesets_by_param_1_evaluations(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/quality/quality/rulesets/{param}/evaluations."""
        return self._request(
            Operation("POST", "/data/quality/quality/rulesets/{param}/evaluations"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_query_query_federated(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/query/query/federated."""
        return self._request(
            Operation("POST", "/data/query/query/federated"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_schemas_schemas(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/schemas/schemas."""
        return self._request(
            Operation("POST", "/data/schemas/schemas"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_schemas_schemas_resolve(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/schemas/schemas/resolve."""
        return self._request(
            Operation("POST", "/data/schemas/schemas/resolve"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_serving_serving_products(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/serving/serving/products."""
        return self._request(
            Operation("POST", "/data/serving/serving/products"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_serving_serving_products_by_param_1_refreshes(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/serving/serving/products/{param}/refreshes."""
        return self._request(
            Operation("POST", "/data/serving/serving/products/{param}/refreshes"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_streams_streams(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/streams/streams."""
        return self._request(
            Operation("POST", "/data/streams/streams"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_streams_streams_by_param_1_deliveries(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/streams/streams/{param}/deliveries."""
        return self._request(
            Operation("POST", "/data/streams/streams/{param}/deliveries"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_sync_sync_jobs(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/sync/sync/jobs."""
        return self._request(
            Operation("POST", "/data/sync/sync/jobs"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_sync_sync_jobs_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/sync/sync/jobs/{param}/executions."""
        return self._request(
            Operation("POST", "/data/sync/sync/jobs/{param}/executions"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_data_transformations_transformations(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/transformations/transformations."""
        return self._request(
            Operation("POST", "/data/transformations/transformations"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_transformations_transformations_by_param_1_executions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/transformations/transformations/{param}/executions."""
        return self._request(
            Operation(
                "POST", "/data/transformations/transformations/{param}/executions"
            ),
            path_params=(param_1,),
            query=query,
            body=body,
        )
