"""Typed API resource for the lineage endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Lineage(APIResource):
    """Methods for the lineage API endpoints."""

    def get_lineage_edges(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /lineage/edges."""
        return self._request(
            Operation("GET", "/lineage/edges"),
            path_params=(),
            query=query,
        )

    def get_lineage_edges_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /lineage/edges/{param}."""
        return self._request(
            Operation("GET", "/lineage/edges/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_lineage_graph(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /lineage/graph."""
        return self._request(
            Operation("GET", "/lineage/graph"),
            path_params=(),
            query=query,
        )

    def get_lineage_nodes(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /lineage/nodes."""
        return self._request(
            Operation("GET", "/lineage/nodes"),
            path_params=(),
            query=query,
        )

    def get_lineage_nodes_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /lineage/nodes/{param}."""
        return self._request(
            Operation("GET", "/lineage/nodes/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_lineage_nodes_by_param_1_trace(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /lineage/nodes/{param}/trace."""
        return self._request(
            Operation("GET", "/lineage/nodes/{param}/trace"),
            path_params=(param_1,),
            query=query,
        )

    def post_lineage_impact(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /lineage/impact."""
        return self._request(
            Operation("POST", "/lineage/impact"),
            path_params=(),
            query=query,
            body=body,
        )
