"""Typed API resource for the observability endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from collections.abc import Iterator

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams, ServerEvent
from frontal_sdk.resources._base import APIResource


class Observability(APIResource):
    """Methods for the observability API endpoints."""

    def delete_observability_alerts_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /observability/alerts/{param}."""
        return self._request(
            Operation("DELETE", "/observability/alerts/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_observability_dashboards_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /observability/dashboards/{param}."""
        return self._request(
            Operation("DELETE", "/observability/dashboards/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_observability_alerts(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/alerts."""
        return self._request(
            Operation("GET", "/observability/alerts"),
            path_params=(),
            query=query,
        )

    def get_observability_alerts_incidents(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/alerts/incidents."""
        return self._request(
            Operation("GET", "/observability/alerts/incidents"),
            path_params=(),
            query=query,
        )

    def get_observability_dashboards(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/dashboards."""
        return self._request(
            Operation("GET", "/observability/dashboards"),
            path_params=(),
            query=query,
        )

    def get_observability_dashboards_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/dashboards/{param}."""
        return self._request(
            Operation("GET", "/observability/dashboards/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_observability_events_stats(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/events/stats."""
        return self._request(
            Operation("GET", "/observability/events/stats"),
            path_params=(),
            query=query,
        )

    def get_observability_metrics(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/metrics."""
        return self._request(
            Operation("GET", "/observability/metrics"),
            path_params=(),
            query=query,
        )

    def get_observability_metrics_list(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/metrics/list."""
        return self._request(
            Operation("GET", "/observability/metrics/list"),
            path_params=(),
            query=query,
        )

    def get_observability_traces(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/traces."""
        return self._request(
            Operation("GET", "/observability/traces"),
            path_params=(),
            query=query,
        )

    def get_observability_traces_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /observability/traces/{param}."""
        return self._request(
            Operation("GET", "/observability/traces/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def post_observability_alerts(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/alerts."""
        return self._request(
            Operation("POST", "/observability/alerts"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_alerts_by_param_1_disable(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/alerts/{param}/disable."""
        return self._request(
            Operation("POST", "/observability/alerts/{param}/disable"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_observability_alerts_by_param_1_enable(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/alerts/{param}/enable."""
        return self._request(
            Operation("POST", "/observability/alerts/{param}/enable"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_observability_dashboards(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/dashboards."""
        return self._request(
            Operation("POST", "/observability/dashboards"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_dashboards_by_param_1_share(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/dashboards/{param}/share."""
        return self._request(
            Operation("POST", "/observability/dashboards/{param}/share"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_observability_events(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/events."""
        return self._request(
            Operation("POST", "/observability/events"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_events_batch(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/events/batch."""
        return self._request(
            Operation("POST", "/observability/events/batch"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_logs_ingest(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/logs/ingest."""
        return self._request(
            Operation("POST", "/observability/logs/ingest"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_logs_query(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/logs/query."""
        return self._request(
            Operation("POST", "/observability/logs/query"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_metrics_ingest(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/metrics/ingest."""
        return self._request(
            Operation("POST", "/observability/metrics/ingest"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_observability_traces_query(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /observability/traces/query."""
        return self._request(
            Operation("POST", "/observability/traces/query"),
            path_params=(),
            query=query,
            body=body,
        )

    def put_observability_alerts_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /observability/alerts/{param}."""
        return self._request(
            Operation("PUT", "/observability/alerts/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_observability_dashboards_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /observability/dashboards/{param}."""
        return self._request(
            Operation("PUT", "/observability/dashboards/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def stream_observability_logs_stream(
        self, *, query: QueryParams | None = None
    ) -> Iterator[ServerEvent]:
        """Call STREAM /observability/logs/stream."""
        return self._stream(
            Operation("STREAM", "/observability/logs/stream"),
            path_params=(),
            query=query,
        )
