"""Typed API resource for the ontology endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Ontology(APIResource):
    """Methods for the ontology API endpoints."""

    def delete_ontology_objects_object_types_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/objects/object-types/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/objects/object-types/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_objects_objects_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/objects/objects/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/objects/objects/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_reasoning_rules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/reasoning/rules/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/reasoning/rules/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_relationships_relationship_types_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/relationships/relationship-types/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/relationships/relationship-types/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_relationships_relationships_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/relationships/relationships/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/relationships/relationships/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_rollouts_rollouts_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/rollouts/rollouts/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/rollouts/rollouts/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_rollups_rollups_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/rollups/rollups/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/rollups/rollups/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_schemas_schemas_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/schemas/schemas/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/schemas/schemas/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_validation_rules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/validation/rules/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/validation/rules/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def delete_ontology_versions_versions_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /ontology/versions/versions/{param}."""
        return self._request(
            Operation("DELETE", "/ontology/versions/versions/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_events_events(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/events/events."""
        return self._request(
            Operation("GET", "/ontology/events/events"),
            path_params=(),
            query=query,
        )

    def get_ontology_events_events_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/events/events/{param}."""
        return self._request(
            Operation("GET", "/ontology/events/events/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_events_events_checkpoints_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/events/events/checkpoints/{param}."""
        return self._request(
            Operation("GET", "/ontology/events/events/checkpoints/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_objects_object_types(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/objects/object-types."""
        return self._request(
            Operation("GET", "/ontology/objects/object-types"),
            path_params=(),
            query=query,
        )

    def get_ontology_objects_object_types_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/objects/object-types/{param}."""
        return self._request(
            Operation("GET", "/ontology/objects/object-types/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_objects_objects(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/objects/objects."""
        return self._request(
            Operation("GET", "/ontology/objects/objects"),
            path_params=(),
            query=query,
        )

    def get_ontology_objects_objects_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/objects/objects/{param}."""
        return self._request(
            Operation("GET", "/ontology/objects/objects/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_reasoning_rules(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/reasoning/rules."""
        return self._request(
            Operation("GET", "/ontology/reasoning/rules"),
            path_params=(),
            query=query,
        )

    def get_ontology_relationships_relationship_types(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/relationships/relationship-types."""
        return self._request(
            Operation("GET", "/ontology/relationships/relationship-types"),
            path_params=(),
            query=query,
        )

    def get_ontology_relationships_relationships(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/relationships/relationships."""
        return self._request(
            Operation("GET", "/ontology/relationships/relationships"),
            path_params=(),
            query=query,
        )

    def get_ontology_relationships_relationships_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/relationships/relationships/{param}."""
        return self._request(
            Operation("GET", "/ontology/relationships/relationships/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_rollouts_rollouts(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollouts/rollouts."""
        return self._request(
            Operation("GET", "/ontology/rollouts/rollouts"),
            path_params=(),
            query=query,
        )

    def get_ontology_rollouts_rollouts_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollouts/rollouts/{param}."""
        return self._request(
            Operation("GET", "/ontology/rollouts/rollouts/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_rollouts_rollouts_by_param_1_status(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollouts/rollouts/{param}/status."""
        return self._request(
            Operation("GET", "/ontology/rollouts/rollouts/{param}/status"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_rollups_rollup_results_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollups/rollup-results/{param}."""
        return self._request(
            Operation("GET", "/ontology/rollups/rollup-results/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_rollups_rollups(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollups/rollups."""
        return self._request(
            Operation("GET", "/ontology/rollups/rollups"),
            path_params=(),
            query=query,
        )

    def get_ontology_rollups_rollups_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollups/rollups/{param}."""
        return self._request(
            Operation("GET", "/ontology/rollups/rollups/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_rollups_rollups_by_param_1_result(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/rollups/rollups/{param}/result."""
        return self._request(
            Operation("GET", "/ontology/rollups/rollups/{param}/result"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_schemas_schemas(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/schemas/schemas."""
        return self._request(
            Operation("GET", "/ontology/schemas/schemas"),
            path_params=(),
            query=query,
        )

    def get_ontology_schemas_schemas_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/schemas/schemas/{param}."""
        return self._request(
            Operation("GET", "/ontology/schemas/schemas/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_validation_rules(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/validation/rules."""
        return self._request(
            Operation("GET", "/ontology/validation/rules"),
            path_params=(),
            query=query,
        )

    def get_ontology_validation_rules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/validation/rules/{param}."""
        return self._request(
            Operation("GET", "/ontology/validation/rules/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_versions_release_bundles(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/versions/release-bundles."""
        return self._request(
            Operation("GET", "/ontology/versions/release-bundles"),
            path_params=(),
            query=query,
        )

    def get_ontology_versions_release_bundles_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/versions/release-bundles/{param}."""
        return self._request(
            Operation("GET", "/ontology/versions/release-bundles/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_ontology_versions_versions_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /ontology/versions/versions/{param}."""
        return self._request(
            Operation("GET", "/ontology/versions/versions/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def post_ontology_engine_ontologies_compare_versions(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/compare-versions."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/compare-versions"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_export(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/export."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/export"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_export_shacl(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/export-shacl."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/export-shacl"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_generate(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/generate."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/generate"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_infer_classes(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/infer-classes."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/infer-classes"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_infer_properties(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/infer-properties."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/infer-properties"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_engine_ontologies_validate(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/engine/ontologies/validate."""
        return self._request(
            Operation("POST", "/ontology/engine/ontologies/validate"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_events_events(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/events/events."""
        return self._request(
            Operation("POST", "/ontology/events/events"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_events_events_checkpoints(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/events/events/checkpoints."""
        return self._request(
            Operation("POST", "/ontology/events/events/checkpoints"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_events_events_leases_acknowledge(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/events/events/leases/acknowledge."""
        return self._request(
            Operation("POST", "/ontology/events/events/leases/acknowledge"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_events_events_leases_acquire(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/events/events/leases/acquire."""
        return self._request(
            Operation("POST", "/ontology/events/events/leases/acquire"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_analyze(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/analyze."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/analyze"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_architecture(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/architecture."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/architecture"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_coreferences(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/coreferences."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/coreferences"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_entities(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/entities."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/entities"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_events(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/events."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/events"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_relations(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/relations."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/relations"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_extract_extract_triplets(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/extract/extract/triplets."""
        return self._request(
            Operation("POST", "/ontology/extract/extract/triplets"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_explain(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/explain."""
        return self._request(
            Operation("POST", "/ontology/reasoning/explain"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_facts(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/facts."""
        return self._request(
            Operation("POST", "/ontology/reasoning/facts"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_facts_load_graph(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/facts/load-graph."""
        return self._request(
            Operation("POST", "/ontology/reasoning/facts/load-graph"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_reason_backward(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/reason/backward."""
        return self._request(
            Operation("POST", "/ontology/reasoning/reason/backward"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_reason_forward(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/reason/forward."""
        return self._request(
            Operation("POST", "/ontology/reasoning/reason/forward"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_reasoning_rules(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/reasoning/rules."""
        return self._request(
            Operation("POST", "/ontology/reasoning/rules"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_rollouts_rollouts(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollouts/rollouts."""
        return self._request(
            Operation("POST", "/ontology/rollouts/rollouts"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_rollouts_rollouts_by_param_1_pause(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollouts/rollouts/{param}/pause."""
        return self._request(
            Operation("POST", "/ontology/rollouts/rollouts/{param}/pause"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_rollouts_rollouts_by_param_1_resume(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollouts/rollouts/{param}/resume."""
        return self._request(
            Operation("POST", "/ontology/rollouts/rollouts/{param}/resume"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_rollouts_rollouts_by_param_1_rollback(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollouts/rollouts/{param}/rollback."""
        return self._request(
            Operation("POST", "/ontology/rollouts/rollouts/{param}/rollback"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_rollouts_rollouts_by_param_1_start(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollouts/rollouts/{param}/start."""
        return self._request(
            Operation("POST", "/ontology/rollouts/rollouts/{param}/start"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_rollups_rollups(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollups/rollups."""
        return self._request(
            Operation("POST", "/ontology/rollups/rollups"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_rollups_rollups_by_param_1_execute(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollups/rollups/{param}/execute."""
        return self._request(
            Operation("POST", "/ontology/rollups/rollups/{param}/execute"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_rollups_rollups_by_param_1_preview(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/rollups/rollups/{param}/preview."""
        return self._request(
            Operation("POST", "/ontology/rollups/rollups/{param}/preview"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_ontology_schemas_schemas(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/schemas/schemas."""
        return self._request(
            Operation("POST", "/ontology/schemas/schemas"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_schemas_schemas_validate(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/schemas/schemas/validate."""
        return self._request(
            Operation("POST", "/ontology/schemas/schemas/validate"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_transformations_transformations(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/transformations/transformations."""
        return self._request(
            Operation("POST", "/ontology/transformations/transformations"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_validation_payloads_validate(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/validation/payloads/validate."""
        return self._request(
            Operation("POST", "/ontology/validation/payloads/validate"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_validation_rules(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/validation/rules."""
        return self._request(
            Operation("POST", "/ontology/validation/rules"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_versions_audit_verify(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/versions/audit/verify."""
        return self._request(
            Operation("POST", "/ontology/versions/audit/verify"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_versions_release_bundles(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/versions/release-bundles."""
        return self._request(
            Operation("POST", "/ontology/versions/release-bundles"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_versions_versions(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/versions/versions."""
        return self._request(
            Operation("POST", "/ontology/versions/versions"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_ontology_versions_versions_compare(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /ontology/versions/versions/compare."""
        return self._request(
            Operation("POST", "/ontology/versions/versions/compare"),
            path_params=(),
            query=query,
            body=body,
        )

    def put_ontology_objects_object_types_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/objects/object-types/{param}."""
        return self._request(
            Operation("PUT", "/ontology/objects/object-types/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_ontology_objects_objects_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/objects/objects/{param}."""
        return self._request(
            Operation("PUT", "/ontology/objects/objects/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_ontology_reasoning_rules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/reasoning/rules/{param}."""
        return self._request(
            Operation("PUT", "/ontology/reasoning/rules/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_ontology_relationships_relationships_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/relationships/relationships/{param}."""
        return self._request(
            Operation("PUT", "/ontology/relationships/relationships/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_ontology_rollouts_rollouts_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/rollouts/rollouts/{param}."""
        return self._request(
            Operation("PUT", "/ontology/rollouts/rollouts/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def put_ontology_rollups_rollups_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PUT /ontology/rollups/rollups/{param}."""
        return self._request(
            Operation("PUT", "/ontology/rollups/rollups/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )
