"""Typed API resource for the pipelines endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from collections.abc import Iterator

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams, ServerEvent
from frontal_sdk.resources._base import APIResource


class Pipelines(APIResource):
    """Methods for the pipelines API endpoints."""

    def get_data_pipelines_capabilities(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/capabilities."""
        return self._request(
            Operation("GET", "/data/pipelines/capabilities"),
            path_params=(),
            query=query,
        )

    def get_data_pipelines_health(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/health."""
        return self._request(
            Operation("GET", "/data/pipelines/health"),
            path_params=(),
            query=query,
        )

    def get_data_pipelines_info(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /data/pipelines/info."""
        return self._request(
            Operation("GET", "/data/pipelines/info"),
            path_params=(),
            query=query,
        )

    def get_data_pipelines_pipeline_runs(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/pipeline-runs."""
        return self._request(
            Operation("GET", "/data/pipelines/pipeline-runs"),
            path_params=(),
            query=query,
        )

    def get_data_pipelines_pipeline_runs_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/pipeline-runs/{param}."""
        return self._request(
            Operation("GET", "/data/pipelines/pipeline-runs/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_pipelines_pipelines(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/pipelines."""
        return self._request(
            Operation("GET", "/data/pipelines/pipelines"),
            path_params=(),
            query=query,
        )

    def get_data_pipelines_pipelines_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /data/pipelines/pipelines/{param}."""
        return self._request(
            Operation("GET", "/data/pipelines/pipelines/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_data_pipelines_runs(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /data/pipelines/runs."""
        return self._request(
            Operation("GET", "/data/pipelines/runs"),
            path_params=(),
            query=query,
        )

    def post_data_pipelines_pipelines(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/pipelines/pipelines."""
        return self._request(
            Operation("POST", "/data/pipelines/pipelines"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_data_pipelines_runs(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /data/pipelines/runs."""
        return self._request(
            Operation("POST", "/data/pipelines/runs"),
            path_params=(),
            query=query,
            body=body,
        )

    def stream_data_pipelines_pipeline_runs_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> Iterator[ServerEvent]:
        """Call STREAM /data/pipelines/pipeline-runs/{param}."""
        return self._stream(
            Operation("STREAM", "/data/pipelines/pipeline-runs/{param}"),
            path_params=(param_1,),
            query=query,
        )
