"""Typed API resource for the schedules endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Schedules(APIResource):
    """Methods for the schedules API endpoints."""

    def delete_workflows_schedules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /workflows/schedules/{param}."""
        return self._request(
            Operation("DELETE", "/workflows/schedules/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_schedules(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /workflows/schedules."""
        return self._request(
            Operation("GET", "/workflows/schedules"),
            path_params=(),
            query=query,
        )

    def get_workflows_schedules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/schedules/{param}."""
        return self._request(
            Operation("GET", "/workflows/schedules/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def patch_workflows_schedules_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PATCH /workflows/schedules/{param}."""
        return self._request(
            Operation("PATCH", "/workflows/schedules/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_cron_parse(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/cron/parse."""
        return self._request(
            Operation("POST", "/workflows/cron/parse"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_cron_validate(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/cron/validate."""
        return self._request(
            Operation("POST", "/workflows/cron/validate"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_schedules(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/schedules."""
        return self._request(
            Operation("POST", "/workflows/schedules"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_schedules_by_param_1_pause(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/schedules/{param}/pause."""
        return self._request(
            Operation("POST", "/workflows/schedules/{param}/pause"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_schedules_by_param_1_resume(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/schedules/{param}/resume."""
        return self._request(
            Operation("POST", "/workflows/schedules/{param}/resume"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_schedules_by_param_1_trigger(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/schedules/{param}/trigger."""
        return self._request(
            Operation("POST", "/workflows/schedules/{param}/trigger"),
            path_params=(param_1,),
            query=query,
            body=body,
        )
