"""Typed API resource for the workflows endpoints.

Generated by ``scripts/generate_resources.py``.

"""

from __future__ import annotations

from frontal_sdk.core.operation import Operation
from frontal_sdk.models import JSONValue, QueryParams
from frontal_sdk.resources._base import APIResource


class Workflows(APIResource):
    """Methods for the workflows API endpoints."""

    def delete_workflows_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call DELETE /workflows/{param}."""
        return self._request(
            Operation("DELETE", "/workflows/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /workflows."""
        return self._request(
            Operation("GET", "/workflows"),
            path_params=(),
            query=query,
        )

    def get_workflows_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/{param}."""
        return self._request(
            Operation("GET", "/workflows/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_approvals(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /workflows/approvals."""
        return self._request(
            Operation("GET", "/workflows/approvals"),
            path_params=(),
            query=query,
        )

    def get_workflows_approvals_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/approvals/{param}."""
        return self._request(
            Operation("GET", "/workflows/approvals/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_executions(
        self, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/executions."""
        return self._request(
            Operation("GET", "/workflows/executions"),
            path_params=(),
            query=query,
        )

    def get_workflows_executions_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/executions/{param}."""
        return self._request(
            Operation("GET", "/workflows/executions/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_executions_by_param_1_tasks(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/executions/{param}/tasks."""
        return self._request(
            Operation("GET", "/workflows/executions/{param}/tasks"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_runs_by_param_1_steps(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/runs/{param}/steps."""
        return self._request(
            Operation("GET", "/workflows/runs/{param}/steps"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_tasks_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/tasks/{param}."""
        return self._request(
            Operation("GET", "/workflows/tasks/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def get_workflows_templates(self, *, query: QueryParams | None = None) -> JSONValue:
        """Call GET /workflows/templates."""
        return self._request(
            Operation("GET", "/workflows/templates"),
            path_params=(),
            query=query,
        )

    def get_workflows_templates_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None
    ) -> JSONValue:
        """Call GET /workflows/templates/{param}."""
        return self._request(
            Operation("GET", "/workflows/templates/{param}"),
            path_params=(param_1,),
            query=query,
        )

    def patch_workflows_by_param_1(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call PATCH /workflows/{param}."""
        return self._request(
            Operation("PATCH", "/workflows/{param}"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows."""
        return self._request(
            Operation("POST", "/workflows"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_by_param_1_archive(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/{param}/archive."""
        return self._request(
            Operation("POST", "/workflows/{param}/archive"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_by_param_1_publish(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/{param}/publish."""
        return self._request(
            Operation("POST", "/workflows/{param}/publish"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_by_param_1_restore(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/{param}/restore."""
        return self._request(
            Operation("POST", "/workflows/{param}/restore"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_by_param_1_versions(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/{param}/versions."""
        return self._request(
            Operation("POST", "/workflows/{param}/versions"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_approvals_by_param_1_approve(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/approvals/{param}/approve."""
        return self._request(
            Operation("POST", "/workflows/approvals/{param}/approve"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_approvals_by_param_1_reject(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/approvals/{param}/reject."""
        return self._request(
            Operation("POST", "/workflows/approvals/{param}/reject"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_executions(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/executions."""
        return self._request(
            Operation("POST", "/workflows/executions"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_tasks_by_param_1_cancel(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/tasks/{param}/cancel."""
        return self._request(
            Operation("POST", "/workflows/tasks/{param}/cancel"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_tasks_by_param_1_retry(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/tasks/{param}/retry."""
        return self._request(
            Operation("POST", "/workflows/tasks/{param}/retry"),
            path_params=(param_1,),
            query=query,
            body=body,
        )

    def post_workflows_templates(
        self, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/templates."""
        return self._request(
            Operation("POST", "/workflows/templates"),
            path_params=(),
            query=query,
            body=body,
        )

    def post_workflows_templates_by_param_1_instantiate(
        self, param_1: str, *, query: QueryParams | None = None, body: JSONValue = None
    ) -> JSONValue:
        """Call POST /workflows/templates/{param}/instantiate."""
        return self._request(
            Operation("POST", "/workflows/templates/{param}/instantiate"),
            path_params=(param_1,),
            query=query,
            body=body,
        )
